package com.cqu.coit13230.AIBasedCustomerSupport.security;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.Date;

import javax.crypto.SecretKey;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import com.cqu.coit13230.AIBasedCustomerSupport.model.User;

import io.jsonwebtoken.Claims;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

/**
 * Provides JWT creation, claim extraction, and validation services
 * for authentication within the AI-based customer support system.
 *
 * <p>
 * JWTs generated by this service contain the user's email address as
 * the token subject together with the user's identifier and role as
 * additional claims. Tokens are signed using the configured secret key
 * and remain valid for the configured expiration period.
 * </p>
 *
 * <p>
 * The service also verifies token signatures, extracts authentication
 * information, and checks whether a token belongs to the expected user
 * and has not expired.
 * </p>
 */
@Service
public class JwtService {

    /**
     * Secret key used to cryptographically sign and verify JWTs.
     */
    private final SecretKey signingKey;

    /**
     * Token validity duration in milliseconds.
     */
    private final long expirationTime;

    /**
     * Creates the JWT service using the configured signing secret and
     * token expiration duration.
     *
     * <p>
     * The configured secret is converted into a cryptographic HMAC key,
     * while the expiration duration is converted from minutes to
     * milliseconds for use when generating tokens.
     * </p>
     *
     * @param secret            secret value used to create the JWT signing key
     * @param expirationMinutes number of minutes for which a generated
     *                          JWT remains valid
     */
    public JwtService(
            @Value("${app.jwt.secret}") String secret,
            @Value("${app.jwt.expiration-minutes}") long expirationMinutes) {

        this.signingKey = Keys.hmacShaKeyFor(
                secret.getBytes(StandardCharsets.UTF_8));

        this.expirationTime = Duration.ofMinutes(expirationMinutes).toMillis();
    }

    /**
     * Generates a signed JWT for the specified user.
     *
     * <p>
     * The user's email address is stored as the token subject, while
     * the user identifier and role are stored as additional claims.
     * The token also contains its issue time and calculated expiration
     * time before being signed with the configured signing key.
     * </p>
     *
     * @param user user for whom the authentication token is generated
     * @return signed JWT containing the user's identity and role
     */
    public String generateToken(User user) {

        Date issuedAt = new Date();
        Date expiration = new Date(issuedAt.getTime() + expirationTime);

        return Jwts.builder()
                .subject(user.getEmail())
                .claim("userId", user.getUserId())
                .claim("role", user.getRole().name())
                .issuedAt(issuedAt)
                .expiration(expiration)
                .signWith(signingKey)
                .compact();
    }

    /**
     * Extracts the user's email address from the subject of a JWT.
     *
     * @param token JWT from which the email address is extracted
     * @return email address stored as the token subject
     */
    public String extractEmail(String token) {
        return extractClaims(token).getSubject();
    }

    /**
     * Extracts the user's role from the {@code role} claim of a JWT.
     *
     * @param token JWT from which the role is extracted
     * @return role stored within the token
     */
    public String extractRole(String token) {
        return extractClaims(token).get("role", String.class);
    }

    /**
     * Determines whether a JWT is valid for the specified user email.
     *
     * <p>
     * A token is considered valid when its signature and claims can be
     * successfully processed, its subject matches the supplied email
     * address without considering letter case, and its expiration time
     * has not passed.
     * </p>
     *
     * <p>
     * If token parsing or validation produces an exception, the token
     * is treated as invalid.
     * </p>
     *
     * @param token JWT to validate
     * @param email expected email address of the authenticated user
     * @return {@code true} if the token belongs to the specified user
     *         and has not expired; otherwise {@code false}
     */
    public boolean isTokenValid(String token, String email) {

        try {
            Claims claims = extractClaims(token);

            return claims.getSubject().equalsIgnoreCase(email)
                    && claims.getExpiration().after(new Date());

        } catch (Exception ex) {
            return false;
        }
    }

    /**
     * Parses a JWT and retrieves its claims after verifying its
     * cryptographic signature.
     *
     * <p>
     * The configured signing key is used to verify the token before
     * the claims payload is returned.
     * </p>
     *
     * @param token JWT whose claims are to be extracted
     * @return verified claims contained within the token
     */
    private Claims extractClaims(String token) {

        return Jwts.parser()
                .verifyWith(signingKey)
                .build()
                .parseSignedClaims(token)
                .getPayload();
    }

}