package com.cqu.coit13230.AIBasedCustomerSupport.controller;

import java.time.LocalDate;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.cqu.coit13230.AIBasedCustomerSupport.dto.AnalyticsReportResponse;
import com.cqu.coit13230.AIBasedCustomerSupport.dto.AnalyticsSummaryResponse;
import com.cqu.coit13230.AIBasedCustomerSupport.model.TicketCategory;
import com.cqu.coit13230.AIBasedCustomerSupport.model.TicketPriority;
import com.cqu.coit13230.AIBasedCustomerSupport.model.TicketStatus;
import com.cqu.coit13230.AIBasedCustomerSupport.service.AnalyticsService;

/**
 * Provides administrator endpoints for ticket analytics and reports.
 *
 * <p>
 * This controller exposes REST API operations for retrieving ticket
 * analytics summaries, filtered analytics results, weekly reports,
 * and monthly reports.
 * </p>
 *
 * <p>
 * Analytics and reporting parameters received through the API are
 * passed to the analytics service, which performs the required
 * calculations and prepares the response data.
 * </p>
 */
@RestController
@RequestMapping("/api")
public class AnalyticsController {

    private final AnalyticsService analyticsService;

    /**
     * Creates the analytics controller with the required analytics service.
     *
     * @param analyticsService service responsible for generating ticket
     *                         analytics and reports
     */
    public AnalyticsController(AnalyticsService analyticsService) {

        this.analyticsService = analyticsService;

    }

    /**
     * Retrieves the overall ticket analytics summary.
     *
     * <p>
     * The summary contains analytics information generated by the
     * analytics service for the available ticket data.
     * </p>
     *
     * @return a response containing the ticket analytics summary
     */
    @GetMapping("/analytics/summary")
    public ResponseEntity<AnalyticsSummaryResponse> getSummary() {

        return ResponseEntity.ok(analyticsService.getTicketSummary());

    }

    /**
     * Retrieves the ticket analytics summary through the administrator
     * analytics endpoint.
     *
     * @return a response containing the ticket analytics summary
     */
    @GetMapping("/admin/analytics/tickets")
    public ResponseEntity<AnalyticsSummaryResponse> getTicketSummary() {

        return ResponseEntity.ok(analyticsService.getTicketSummary());

    }

    /**
     * Retrieves a filtered ticket analytics summary using optional
     * filtering criteria.
     *
     * <p>
     * All filter values are optional so that the same endpoint can support
     * different dashboard searches. Filters can be applied using a date
     * range, ticket category, priority, status, and sentiment-score range.
     * </p>
     *
     * @param startDate    optional start date used to filter ticket data
     * @param endDate      optional end date used to filter ticket data
     * @param category     optional ticket category used for filtering
     * @param priority     optional ticket priority used for filtering
     * @param status       optional ticket status used for filtering
     * @param minSentiment optional minimum sentiment score
     * @param maxSentiment optional maximum sentiment score
     * @return a response containing the filtered ticket analytics summary
     */
    @GetMapping("/admin/analytics/tickets/filter")
    public ResponseEntity<AnalyticsSummaryResponse> getFilteredTicketSummary(

            @RequestParam(required = false) LocalDate startDate,

            @RequestParam(required = false) LocalDate endDate,

            @RequestParam(required = false) TicketCategory category,

            @RequestParam(required = false) TicketPriority priority,

            @RequestParam(required = false) TicketStatus status,

            @RequestParam(required = false) Double minSentiment,

            @RequestParam(required = false) Double maxSentiment) {

        return ResponseEntity.ok(

                analyticsService.getFilteredTicketSummary(

                        startDate,

                        endDate,

                        category,

                        priority,

                        status,

                        minSentiment,

                        maxSentiment));

    }

    /**
     * Generates a weekly analytics report based on the supplied date.
     *
     * <p>
     * The provided date is passed to the analytics service to determine
     * and generate the corresponding weekly report.
     * </p>
     *
     * @param date date used to generate the weekly analytics report
     * @return a response containing the generated weekly analytics report
     */
    @GetMapping("/admin/analytics/reports/weekly")
    public ResponseEntity<AnalyticsReportResponse> getWeeklyReport(

            @RequestParam LocalDate date) {

        return ResponseEntity.ok(analyticsService.getWeeklyReport(date));

    }

    /**
     * Generates a monthly analytics report based on the supplied date.
     *
     * <p>
     * The provided date is passed to the analytics service to determine
     * and generate the corresponding monthly report.
     * </p>
     *
     * @param date date used to generate the monthly analytics report
     * @return a response containing the generated monthly analytics report
     */
    @GetMapping("/admin/analytics/reports/monthly")
    public ResponseEntity<AnalyticsReportResponse> getMonthlyReport(

            @RequestParam LocalDate date) {

        return ResponseEntity.ok(analyticsService.getMonthlyReport(date));

    }

}