package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Stores a customer support conversation.
 *
 * <p>
 * This JPA entity represents a conversation created between a customer
 * and the AI-based customer support system. It stores the customer
 * associated with the conversation, the current conversation status,
 * and the timestamps representing when the conversation started and ended.
 * </p>
 *
 * <p>
 * The model is persisted in the {@code conversations} database table
 * and is used by the related service and repository classes.
 * </p>
 */
@Entity
@Table(name = "conversations")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Conversation {

    /**
     * Unique identifier of the conversation.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long conversationId;

    /**
     * Customer associated with the conversation.
     *
     * <p>
     * Each conversation must belong to a customer. The relationship
     * is stored using the {@code customer_id} foreign key column.
     * </p>
     */
    @NotNull(message = "Customer is required")
    @ManyToOne(optional = false)
    @JoinColumn(name = "customer_id", nullable = false)
    private User customer;

    /**
     * Current status of the customer support conversation.
     *
     * <p>
     * The status is required and is stored in the database as its
     * string representation. New conversations default to
     * {@link ConversationStatus#ACTIVE}.
     * </p>
     */
    @NotNull(message = "Conversation status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private ConversationStatus status = ConversationStatus.ACTIVE;

    /**
     * Date and time when the conversation started.
     *
     * <p>
     * This value cannot be updated after the entity has been created.
     * If no value is supplied before persistence, it is automatically
     * assigned by the {@link #onCreate()} method.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime startedAt;

    /**
     * Date and time when the conversation ended.
     *
     * <p>
     * This value may remain {@code null} while the conversation is
     * still active.
     * </p>
     */
    private LocalDateTime endedAt;

    /**
     * Initializes the conversation creation timestamp before the
     * entity is persisted.
     *
     * <p>
     * If {@code startedAt} has not already been provided, the current
     * date and time are assigned automatically.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        if (startedAt == null) {

            startedAt = LocalDateTime.now();

        }

    }

}