package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents an entry in the customer support knowledge base.
 *
 * <p>
 * Each knowledge base entry contains a question pattern, an answer
 * template, and a category that can be used by the customer support
 * system when responding to customer enquiries.
 * </p>
 *
 * <p>
 * The entity also stores whether the entry is active, the user who
 * last updated it, and the date and time of the most recent update.
 * The data is persisted in the {@code knowledge_base_entries} table.
 * </p>
 */
@Entity
@Table(name = "knowledge_base_entries")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class KnowledgeBaseEntry {

    /**
     * Unique identifier of the knowledge base entry.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long kbId;

    /**
     * Question pattern associated with the knowledge base entry.
     *
     * <p>
     * This value is required and can contain up to 500 characters.
     * It represents the type of customer question associated with
     * the stored answer template.
     * </p>
     */
    @NotBlank(message = "Question pattern is required")
    @Column(nullable = false, length = 500)
    private String questionPattern;

    /**
     * Answer template associated with the question pattern.
     *
     * <p>
     * This value is required and is stored as text so that the
     * knowledge base can contain detailed support responses.
     * </p>
     */
    @NotBlank(message = "Answer template is required")
    @Column(nullable = false, columnDefinition = "TEXT")
    private String answerTemplate;

    /**
     * Category assigned to the knowledge base entry.
     *
     * <p>
     * The category is required and is used to organise knowledge
     * base entries according to the type of customer enquiry.
     * </p>
     */
    @NotBlank(message = "Category is required")
    @Column(nullable = false, length = 50)
    private String category;

    /**
     * Indicates whether the knowledge base entry is currently active.
     *
     * <p>
     * New entries are active by default. An inactive entry can remain
     * stored in the database without being treated as an active
     * knowledge base entry.
     * </p>
     */
    @Column(nullable = false)
    private Boolean active = true;

    /**
     * User who most recently updated the knowledge base entry.
     *
     * <p>
     * This field defines a many-to-one relationship with the
     * {@link User} entity and is stored using the
     * {@code last_updated_by} foreign key column.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "last_updated_by")
    private User lastUpdatedBy;

    /**
     * Date and time when the knowledge base entry was last updated.
     *
     * <p>
     * This value is automatically refreshed whenever the entity
     * is created or updated.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime lastUpdatedAt;

    /**
     * Updates the knowledge base entry timestamp before the entity
     * is created or updated.
     *
     * <p>
     * The current date and time are assigned to {@code lastUpdatedAt}.
     * If the {@code active} value is {@code null}, it is automatically
     * set to {@code true}.
     * </p>
     */
    @PrePersist
    @PreUpdate
    protected void updateTimestamp() {

        lastUpdatedAt = LocalDateTime.now();

        if (active == null) {

            active = true;

        }

    }

}