package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a message sent within a customer support conversation.
 *
 * <p>
 * Each message is associated with a conversation and stores information
 * about the sender, sender type, message content, sentiment, sentiment
 * score, and creation timestamp.
 * </p>
 *
 * <p>
 * The entity is persisted in the {@code messages} database table and
 * supports storing messages exchanged between customers, support agents,
 * and the AI-based customer support system.
 * </p>
 */
@Entity
@Table(name = "messages")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Message {

    /**
     * Unique identifier of the message.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long messageId;

    /**
     * Conversation associated with the message.
     *
     * <p>
     * Every message must belong to a conversation. The relationship
     * is stored using the {@code conversation_id} foreign key column.
     * </p>
     */
    @NotNull(message = "Conversation is required")
    @ManyToOne(optional = false)
    @JoinColumn(name = "conversation_id", nullable = false)
    private Conversation conversation;

    /**
     * User who sent the message.
     *
     * <p>
     * This field defines a many-to-one relationship with the
     * {@link User} entity and is stored using the
     * {@code sender_user_id} foreign key column.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "sender_user_id")
    private User senderUser;

    /**
     * Type of sender responsible for the message.
     *
     * <p>
     * The sender type is required and is stored in the database
     * using the string representation of the {@link SenderType}
     * enumeration.
     * </p>
     */
    @NotNull(message = "Sender type is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private SenderType senderType;

    /**
     * Text content of the support message.
     *
     * <p>
     * The message content is required and is stored as text to
     * support longer customer, agent, or AI-generated responses.
     * </p>
     */
    @NotBlank(message = "Message content is required")
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /**
     * Sentiment classification associated with the message.
     *
     * <p>
     * The sentiment is stored using the string representation of
     * the {@link Sentiment} enumeration and defaults to
     * {@link Sentiment#NEUTRAL}.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private Sentiment sentiment = Sentiment.NEUTRAL;

    /**
     * Numerical sentiment score associated with the message.
     *
     * <p>
     * This value can be used alongside the sentiment classification
     * to represent the analysed sentiment of the message.
     * </p>
     */
    private Double sentimentScore;

    /**
     * Date and time when the message was created.
     *
     * <p>
     * This value is assigned automatically before the entity is
     * persisted and cannot be updated afterwards.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Initializes values required when the message is first persisted.
     *
     * <p>
     * The current date and time are assigned to {@code createdAt}.
     * If no sentiment has been provided, the sentiment is automatically
     * set to {@link Sentiment#NEUTRAL}.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        createdAt = LocalDateTime.now();

        if (sentiment == null) {

            sentiment = Sentiment.NEUTRAL;

        }

    }

}