package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a notification created for a user within the
 * AI-based customer support system.
 *
 * <p>
 * Each notification is associated with a system user and may also
 * reference a support ticket. It stores the notification message,
 * read status, and creation timestamp.
 * </p>
 *
 * <p>
 * The entity is persisted in the {@code notifications} database table
 * and can be used to inform users about ticket-related activities and
 * other relevant system events.
 * </p>
 */
@Entity
@Table(name = "notifications")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    /**
     * Unique identifier of the notification.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long notificationId;

    /**
     * User who receives the notification.
     *
     * <p>
     * Every notification must be associated with a user. The relationship
     * is stored using the {@code user_id} foreign key column.
     * </p>
     */
    @NotNull(message = "User is required")
    @ManyToOne(optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Support ticket associated with the notification.
     *
     * <p>
     * This relationship is optional because a notification may be
     * created without being associated with a specific support ticket.
     * The relationship is stored using the {@code ticket_id} foreign
     * key column.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "ticket_id")
    private Ticket ticket;

    /**
     * Text message displayed in the notification.
     *
     * <p>
     * The notification message is required and can contain up to
     * 500 characters.
     * </p>
     */
    @NotBlank(message = "Notification message is required")
    @Column(nullable = false, length = 500)
    private String message;

    /**
     * Indicates whether the notification has been read by the user.
     *
     * <p>
     * New notifications are unread by default and therefore use
     * {@code false} as the initial value.
     * </p>
     */
    @Column(nullable = false)
    private Boolean isRead = false;

    /**
     * Date and time when the notification was created.
     *
     * <p>
     * This value is assigned automatically before the entity is
     * persisted and cannot be updated afterwards.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Initializes the notification values before the entity is persisted.
     *
     * <p>
     * The current date and time are assigned to {@code createdAt}.
     * If {@code isRead} is {@code null}, it is automatically set
     * to {@code false}.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        createdAt = LocalDateTime.now();

        if (isRead == null) {

            isRead = false;

        }

    }

}