package com.cqu.coit13230.AIBasedCustomerSupport.model;

/**
 * Defines the possible sender types for messages exchanged
 * within a customer support conversation.
 */
public enum SenderType {

    /** Indicates that the message was sent by a customer. */
    CUSTOMER,

    /** Indicates that the message was generated by the AI chatbot. */
    AI,

    /** Indicates that the message was sent by a human support agent. */
    SUPPORT_AGENT
}