package com.cqu.coit13230.AIBasedCustomerSupport.model;

import com.fasterxml.jackson.annotation.JsonCreator;

/**
 * Represents the possible senders of a message within a customer
 * support conversation.
 *
 * <p>
 * A message can be sent by a client, the AI system, a support agent,
 * or the system itself. The enumeration also supports alternative
 * sender labels received through the API by converting them into
 * the corresponding internal sender type.
 * </p>
 */
public enum SenderType {

    /**
     * Indicates that the message was sent by a client.
     */
    CLIENT,

    /**
     * Indicates that the message was generated by the AI system.
     */
    AI,

    /**
     * Indicates that the message was sent by a support agent.
     */
    AGENT,

    /**
     * Indicates that the message was generated by the system.
     */
    SYSTEM;

    /**
     * Converts a sender label received through the API into the
     * corresponding {@code SenderType} value.
     *
     * <p>
     * The supplied value is trimmed and converted to uppercase before
     * processing. The alternative label {@code CUSTOMER} is mapped to
     * {@link #CLIENT}, while {@code SUPPORT_AGENT} is mapped to
     * {@link #AGENT}. Other values are converted using the matching
     * enumeration value.
     * </p>
     *
     * @param value sender label received through the API
     * @return the corresponding sender type, or {@code null} if the
     *         supplied value is {@code null}
     */
    @JsonCreator
    public static SenderType fromValue(String value) {

        if (value == null) {

            return null;

        }

        return switch (value.trim().toUpperCase()) {

            case "CUSTOMER" -> CLIENT;

            case "SUPPORT_AGENT" -> AGENT;

            default -> SenderType.valueOf(value.trim().toUpperCase());

        };

    }

}