package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents an application event recorded for audit and activity
 * tracking within the AI-based customer support system.
 *
 * <p>
 * Each system log stores an event type, description, and creation
 * timestamp. A log may also be associated with a specific user
 * and support ticket when the recorded event relates to them.
 * </p>
 *
 * <p>
 * The entity is persisted in the {@code system_logs} database table
 * and provides a history of important system activities and events.
 * </p>
 */
@Entity
@Table(name = "system_logs")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class SystemLog {

    /**
     * Unique identifier of the system log entry.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long logId;

    /**
     * User associated with the recorded system event.
     *
     * <p>
     * This relationship is optional because some system events may
     * occur without being associated with a specific user. The
     * relationship is stored using the {@code user_id} foreign key.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "user_id")
    private User user;

    /**
     * Support ticket associated with the recorded system event.
     *
     * <p>
     * This relationship is optional because some system events may
     * not relate to a specific support ticket. The relationship is
     * stored using the {@code ticket_id} foreign key.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "ticket_id")
    private Ticket ticket;

    /**
     * Type of application event recorded in the system log.
     *
     * <p>
     * The event type is required and can contain up to 80 characters.
     * It identifies the type of activity represented by the log entry.
     * </p>
     */
    @NotBlank(message = "Event type is required")
    @Column(nullable = false, length = 80)
    private String eventType;

    /**
     * Description of the application event.
     *
     * <p>
     * The description is required and provides additional information
     * about the activity or event recorded in the system log.
     * </p>
     */
    @NotBlank(message = "Description is required")
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description;

    /**
     * Date and time when the system log entry was created.
     *
     * <p>
     * This value is automatically assigned before the entity is
     * persisted and cannot be updated afterwards.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Initializes the creation timestamp before the system log
     * entity is persisted.
     *
     * <p>
     * The current date and time are automatically assigned to
     * {@code createdAt}.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        createdAt = LocalDateTime.now();

    }

}