package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a customer support ticket and its associated AI analysis results.
 *
 * <p>
 * Each ticket is linked to a customer support conversation and customer,
 * and may optionally be assigned to a support agent. The ticket stores
 * information such as its title, category, priority, status, sentiment,
 * AI confidence score, escalation details, and resolution information.
 * </p>
 *
 * <p>
 * The entity also records timestamps for important stages of the ticket
 * lifecycle, including creation, update, escalation, first response,
 * resolution, and closure. The data is persisted in the {@code tickets}
 * database table.
 * </p>
 */
@Entity
@Table(name = "tickets")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Ticket {

    /**
     * Unique identifier of the support ticket.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long ticketId;

    /**
     * Conversation associated with the support ticket.
     *
     * <p>
     * Each ticket must be linked to one conversation. The relationship
     * is stored using the unique {@code conversation_id} foreign key.
     * </p>
     */
    @OneToOne(optional = false)
    @JoinColumn(name = "conversation_id", nullable = false, unique = true)
    private Conversation conversation;

    /**
     * Customer who owns the support ticket.
     *
     * <p>
     * Every ticket must be associated with a customer. The relationship
     * is stored using the {@code customer_id} foreign key.
     * </p>
     */
    @NotNull(message = "Customer is required")
    @ManyToOne(optional = false)
    @JoinColumn(name = "customer_id", nullable = false)
    private User customer;

    /**
     * Support agent currently assigned to the ticket.
     *
     * <p>
     * This relationship is optional because a ticket may exist before
     * a support agent has been assigned. The relationship is stored
     * using the {@code assigned_agent_id} foreign key.
     * </p>
     */
    @ManyToOne
    @JoinColumn(name = "assigned_agent_id")
    private User assignedAgent;

    /**
     * Title describing the support ticket.
     *
     * <p>
     * The title can contain up to 180 characters.
     * </p>
     */
    @Column(length = 180)
    private String title;

    /**
     * Category assigned to the support ticket.
     *
     * <p>
     * The category is required, is stored using its string
     * representation, and defaults to
     * {@link TicketCategory#GENERAL_INQUIRY}.
     * </p>
     */
    @NotNull(message = "Ticket category is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 40)
    private TicketCategory category = TicketCategory.GENERAL_INQUIRY;

    /**
     * Priority level assigned to the support ticket.
     *
     * <p>
     * The priority is required, is stored using its string
     * representation, and defaults to {@link TicketPriority#MEDIUM}.
     * </p>
     */
    @NotNull(message = "Ticket priority is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TicketPriority priority = TicketPriority.MEDIUM;

    /**
     * Current status of the support ticket.
     *
     * <p>
     * The status is required, is stored using its string
     * representation, and defaults to {@link TicketStatus#OPEN}.
     * </p>
     */
    @NotNull(message = "Ticket status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private TicketStatus status = TicketStatus.OPEN;

    /**
     * Sentiment classification associated with the support ticket.
     *
     * <p>
     * The sentiment is stored using its string representation and
     * defaults to {@link Sentiment#NEUTRAL}.
     * </p>
     */
    @Enumerated(EnumType.STRING)
    @Column(length = 20)
    private Sentiment sentiment = Sentiment.NEUTRAL;

    /**
     * Numerical sentiment score associated with the support ticket.
     *
     * <p>
     * The score is constrained to values between {@code -1.0}
     * and {@code 1.0}.
     * </p>
     */
    @DecimalMin("-1.0")
    @DecimalMax("1.0")
    private Double sentimentScore;

    /**
     * Confidence score produced by the AI analysis.
     *
     * <p>
     * The confidence score is constrained to values between
     * {@code 0.0} and {@code 1.0}.
     * </p>
     */
    @DecimalMin("0.0")
    @DecimalMax("1.0")
    private Double aiConfidenceScore;

    /**
     * Reason explaining why the support ticket was escalated.
     *
     * <p>
     * The value is stored as text to support detailed escalation
     * information.
     * </p>
     */
    @Column(columnDefinition = "TEXT")
    private String escalationReason;

    /**
     * Notes describing how the support ticket was resolved.
     *
     * <p>
     * The value is stored as text to support detailed resolution
     * information.
     * </p>
     */
    @Column(columnDefinition = "TEXT")
    private String resolutionNotes;

    /**
     * Date and time when the support ticket was created.
     *
     * <p>
     * This value is automatically assigned when the entity is first
     * persisted and cannot be updated afterwards.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Date and time when the support ticket was most recently updated.
     *
     * <p>
     * This value is initialized when the ticket is created and refreshed
     * whenever the entity is updated.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Date and time when the support ticket was escalated.
     *
     * <p>
     * This value can be used to preserve the historical escalation
     * event even if the ticket later moves to another status.
     * </p>
     */
    private LocalDateTime escalatedAt;

    /**
     * Date and time when the first response was recorded for the ticket.
     */
    private LocalDateTime firstResponseAt;

    /**
     * Date and time when the support ticket was resolved.
     */
    private LocalDateTime resolvedAt;

    /**
     * Date and time when the support ticket was closed.
     */
    private LocalDateTime closedAt;

    /**
     * Returns the ticket identifier using the JSON property name
     * {@code id}.
     *
     * @return the unique identifier of the support ticket
     */
    @JsonProperty("id")
    public Long getIdAlias() {

        return ticketId;

    }

    /**
     * Indicates whether the support ticket has been escalated.
     *
     * <p>
     * A ticket is considered escalated when an escalation timestamp
     * exists or when its current status is {@link TicketStatus#ESCALATED}.
     * </p>
     *
     * @return {@code true} if the ticket has been escalated;
     *         otherwise {@code false}
     */
    @JsonProperty("escalated")
    public boolean isEscalated() {

        return escalatedAt != null || status == TicketStatus.ESCALATED;

    }

    /**
     * Initializes the creation and update timestamps before the ticket
     * is first persisted.
     *
     * <p>
     * The current date and time are assigned to both {@code createdAt}
     * and {@code updatedAt}.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        LocalDateTime now = LocalDateTime.now();

        createdAt = now;

        updatedAt = now;

    }

    /**
     * Updates the modification timestamp before an existing ticket
     * is persisted after a change.
     *
     * <p>
     * The current date and time are assigned to {@code updatedAt}.
     * </p>
     */
    @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();

    }

}