package com.cqu.coit13230.AIBasedCustomerSupport.model;

import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/**
 * Represents a user account within the AI-based customer support system.
 *
 * <p>
 * Each user account stores identification details, authentication
 * information, access role, account status, and creation and update
 * timestamps.
 * </p>
 *
 * <p>
 * The entity is persisted in the {@code users} database table. User
 * roles and account statuses are stored as string values, while the
 * password hash is configured as write-only for JSON serialization.
 * </p>
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class User {

    /**
     * Unique identifier of the user.
     *
     * <p>
     * The identifier is automatically generated by the database using
     * the identity generation strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;

    /**
     * Name of the user.
     *
     * <p>
     * The name is required and can contain up to 100 characters.
     * </p>
     */
    @NotBlank(message = "Name is required")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Email address associated with the user account.
     *
     * <p>
     * The email address is required, must use a valid email format,
     * and must be unique within the system. Before persistence or
     * update, the email address is normalized by the
     * {@link #normalizeEmail()} method.
     * </p>
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Column(nullable = false, unique = true, length = 190)
    private String email;

    /**
     * Hashed password associated with the user account.
     *
     * <p>
     * The password hash is required and is configured as write-only
     * for JSON processing so that it is not included when the user
     * entity is serialized in API responses.
     * </p>
     */
    @NotBlank(message = "Password hash is required")
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Column(nullable = false, length = 255)
    private String passwordHash;

    /**
     * Access role assigned to the user.
     *
     * <p>
     * The role is required, is stored using its string representation,
     * and defaults to {@link UserRole#CLIENT}.
     * </p>
     */
    @NotNull(message = "User role is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private UserRole role = UserRole.CLIENT;

    /**
     * Current status of the user account.
     *
     * <p>
     * The status is required, is stored using its string representation,
     * and defaults to {@link UserStatus#ACTIVE}.
     * </p>
     */
    @NotNull(message = "User status is required")
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private UserStatus status = UserStatus.ACTIVE;

    /**
     * Date and time when the user account was created.
     *
     * <p>
     * This value is automatically assigned when the entity is first
     * persisted and cannot be updated afterwards.
     * </p>
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Date and time when the user account was most recently updated.
     *
     * <p>
     * This value is initialized when the account is created and
     * refreshed whenever the entity is updated.
     * </p>
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Returns the user identifier using the JSON property name
     * {@code id}.
     *
     * @return the unique identifier of the user
     */
    @JsonProperty("id")
    public Long getIdAlias() {

        return userId;

    }

    /**
     * Initializes the creation and update timestamps before the user
     * entity is first persisted.
     *
     * <p>
     * The current date and time are assigned to both {@code createdAt}
     * and {@code updatedAt}. The email address is also normalized
     * before the entity is stored.
     * </p>
     */
    @PrePersist
    protected void onCreate() {

        LocalDateTime now = LocalDateTime.now();

        createdAt = now;

        updatedAt = now;

        normalizeEmail();

    }

    /**
     * Updates the modification timestamp before an existing user
     * entity is persisted after a change.
     *
     * <p>
     * The current date and time are assigned to {@code updatedAt},
     * and the email address is normalized before the update is stored.
     * </p>
     */
    @PreUpdate
    protected void onUpdate() {

        updatedAt = LocalDateTime.now();

        normalizeEmail();

    }

    /**
     * Normalizes the user's email address before database persistence.
     *
     * <p>
     * If the email address is not {@code null}, leading and trailing
     * whitespace is removed and the value is converted to lowercase.
     * </p>
     */
    private void normalizeEmail() {

        if (email != null) {

            email = email.trim().toLowerCase();

        }

    }

}